# tasks/main.yml

- name: Install web server package
  yum:
    name: "{{ package_name }}"
    state: present

- name: Ensure web server service is running
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: Create web server users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    state: present
  loop: "{{ users }}"

- name: Gather IP address of the managed host
  set_fact:
    ip_address: "{{ ansible_default_ipv4.address }}"

- name: Display the IP address
  debug:
    msg: "The IP address of this host is {{ ip_address }}"

- name: Deploy web server index page
  template:
    src: index.html
    dest: "{{ web_root }}/index.html"
  notify:
    - Restart web server

